### ISSUE TITLE
Any download link of trained model?

### ISSUE THREAD

**Issue by lizekui** [vishakhpk/mil-creative-captioning#1]
This rewriting model is impressive enough for me. Could someone share a link of trained model? 
I tried to mailto author but did not receive a reply unfortunately~

Thanks firstly!

**Comment by vishakhpk** [comment]
https://github.com/vishakhpk/mil-creative-captioning/commit/cc37c92cab9e10200ad5d93513f23cbe1d545ec0
Thanks for reaching out! Apologies for the delay in getting back to you. I've replied to your mail.
